version: '3.8'

services:
  # Main Application
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=forum
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - AUTH_SERVICE_URL=http://auth:8001
      - NOTIFICATION_SERVICE_URL=http://notification:8002

  # Auth Service
  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    volumes:
      - ./src/Auth:/var/www/html
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=forum
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - db

  # Notification Service
  notification:
    build:
      context: .
      dockerfile: docker/notification/Dockerfile
    volumes:
      - ./src/Notification:/var/www/html
    ports:
      - "8002:8002"
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - mailhog

  # Nginx Web Server  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - auth
      - db

  # PostgreSQL Database
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis for Caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # MailHog for Email Testing
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data: 